# Math Operations on Arrays/Matrices

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
b = np.array([10, 20, 30, 40, 50])

In [4]:
c = a + b

In [5]:
c

array([11, 22, 33, 44, 55])

In [6]:
c / 2.5

array([ 4.4,  8.8, 13.2, 17.6, 22. ])

In [7]:
a / 2.5

array([0.4, 0.8, 1.2, 1.6, 2. ])