## One dimensional array of `int`

In [1]:
import numpy as np

In [2]:
simple_array = np.arange(10)
simple_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Note: An array can only have one type of data in it.

In [4]:
float_array = np.arange(10, dtype=float)
float_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
float_array.dtype

dtype('float64')

In [7]:
complex_array = float_array.astype(complex)
complex_array

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

### Generating a List of numbers Using For Loop

Use the `randint()` method along with a for loop to generate a list of numbers. First create an empty list and then append the random numbers generated to the empty list one by one.

In [10]:
import random
intlist = []
for i in range(0,30):
    n = random.randint(1,1200)
    intlist.append(n)
print(intlist)

[61, 642, 45, 676, 1065, 368, 827, 560, 135, 315, 749, 720, 719, 418, 872, 748, 1071, 1029, 916, 458, 384, 152, 670, 1004, 963, 588, 875, 764, 610, 365]


In [12]:
int_array = np.array(intlist)
int_array

array([  61,  642,   45,  676, 1065,  368,  827,  560,  135,  315,  749,
        720,  719,  418,  872,  748, 1071, 1029,  916,  458,  384,  152,
        670, 1004,  963,  588,  875,  764,  610,  365])

In [13]:
int_array.dtype

dtype('int64')

### Create an array from a file

In [14]:
scores_array = np.genfromtxt('scores.csv', delimiter=',', dtype=int)

In [15]:
scores_array

array([1297,  603, 1071,  539, 1222, 1424,  986,  397,  970, 1102,  499,
        533,  908,  559,  386, 1183,  595,   69, 1141,   76,  863, 1343,
        185,  895, 1312,   50,  918,  677,  394,  629, 1317,  944,  466,
        751, 1050,  301,  415,  784,   19, 1395, 1223,  979,  252, 1155,
         59,  107,  632,  995,  972,  867,  332,  751,  810,   50,   55,
        218,  997, 1085,  475, 1494])

In [16]:
scores_array.size # How many elements are in the array?

60

In [17]:
scores_array[2:5] #slice

array([1071,  539, 1222])

In [18]:
print(scores_array)

[1297  603 1071  539 1222 1424  986  397  970 1102  499  533  908  559
  386 1183  595   69 1141   76  863 1343  185  895 1312   50  918  677
  394  629 1317  944  466  751 1050  301  415  784   19 1395 1223  979
  252 1155   59  107  632  995  972  867  332  751  810   50   55  218
  997 1085  475 1494]


> Note: Printing the `scores_array` removed the delimiter commas and used sapces instead

In [19]:
scores_array ** 0

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
scores_array

array([1297,  603, 1071,  539, 1222, 1424,  986,  397,  970, 1102,  499,
        533,  908,  559,  386, 1183,  595,   69, 1141,   76,  863, 1343,
        185,  895, 1312,   50,  918,  677,  394,  629, 1317,  944,  466,
        751, 1050,  301,  415,  784,   19, 1395, 1223,  979,  252, 1155,
         59,  107,  632,  995,  972,  867,  332,  751,  810,   50,   55,
        218,  997, 1085,  475, 1494])