## One dimensional array of `int`

In [3]:
import numpy as np

In [4]:
simple_array = np.arange(10)
simple_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Note: An array can only have one type of data in it.

In [5]:
float_array = np.arange(10, dtype=float)
float_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
float_array.dtype

dtype('float64')

In [7]:
complex_array = float_array.astype(complex)
complex_array

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

### Generating a List of numbers Using For Loop

Use the `randint()` method along with a for loop to generate a list of numbers. First create an empty list and then append the random numbers generated to the empty list one by one.

In [8]:
import random
intlist = []
for i in range(0,30):
    n = random.randint(1,1200)
    intlist.append(n)
print(intlist)

[423, 1187, 209, 1042, 1118, 773, 8, 787, 770, 1078, 299, 844, 334, 670, 461, 1190, 614, 974, 91, 205, 406, 61, 344, 1009, 481, 918, 940, 393, 1055, 920]


In [9]:
int_array = np.array(intlist)
int_array

array([ 423, 1187,  209, 1042, 1118,  773,    8,  787,  770, 1078,  299,
        844,  334,  670,  461, 1190,  614,  974,   91,  205,  406,   61,
        344, 1009,  481,  918,  940,  393, 1055,  920])

In [10]:
int_array.dtype

dtype('int64')

### Create an array from a file

In [11]:
scores_array = np.genfromtxt('scores.csv', delimiter=',', dtype=int)

In [12]:
scores_array

array([1297,  603, 1071,  539, 1222, 1424,  986,  397,  970, 1102,  499,
        533,  908,  559,  386, 1183,  595,   69, 1141,   76,  863, 1343,
        185,  895, 1312,   50,  918,  677,  394,  629, 1317,  944,  466,
        751, 1050,  301,  415,  784,   19, 1395, 1223,  979,  252, 1155,
         59,  107,  632,  995,  972,  867,  332,  751,  810,   50,   55,
        218,  997, 1085,  475, 1494])

In [13]:
scores_array.size # How many elements are in the array?

60

In [14]:
scores_array[2:5] #slice

array([1071,  539, 1222])

In [15]:
print(scores_array)

[1297  603 1071  539 1222 1424  986  397  970 1102  499  533  908  559
  386 1183  595   69 1141   76  863 1343  185  895 1312   50  918  677
  394  629 1317  944  466  751 1050  301  415  784   19 1395 1223  979
  252 1155   59  107  632  995  972  867  332  751  810   50   55  218
  997 1085  475 1494]


> Note: Printing the `scores_array` removed the delimiter commas and used sapces instead

In [16]:
scores_array ** 0

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
scores_array

array([1297,  603, 1071,  539, 1222, 1424,  986,  397,  970, 1102,  499,
        533,  908,  559,  386, 1183,  595,   69, 1141,   76,  863, 1343,
        185,  895, 1312,   50,  918,  677,  394,  629, 1317,  944,  466,
        751, 1050,  301,  415,  784,   19, 1395, 1223,  979,  252, 1155,
         59,  107,  632,  995,  972,  867,  332,  751,  810,   50,   55,
        218,  997, 1085,  475, 1494])

## Reshaping a Numpy Array Into a Matrix

In [18]:
int_array = np.array(intlist)

In [19]:
print(int_array)

[ 423 1187  209 1042 1118  773    8  787  770 1078  299  844  334  670
  461 1190  614  974   91  205  406   61  344 1009  481  918  940  393
 1055  920]


In [20]:
int_array.shape

(30,)

In [22]:
int_matrix = int_array.reshape(10, 3)

In [23]:
int_matrix.shape

(10, 3)

In [24]:
a = np.array([1, 2, 3])

In [25]:
print(a)

[1 2 3]


In [26]:
b = np.array([4, 5, 6])

In [27]:
print(b)

[4 5 6]


In [28]:
c = np.vstack((a,b))

In [29]:
print(c)

[[1 2 3]
 [4 5 6]]


In [30]:
d = np.hstack((a,b))

In [31]:
print(d)

[1 2 3 4 5 6]


In [32]:
e = np.hstack(('abcde','12345'))

In [33]:
print(e)

['abcde' '12345']


In [35]:
np.hstack((a,b,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)

In [36]:
a = np.array([[1, 2], [3, 4]])

In [37]:
b = np.array([[5, 6]])

In [38]:
np.concatenate((a,b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [39]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
b = np.array([5])

In [41]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [43]:
b = np.array([[5, 6]])

In [44]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [45]:
b = np.array([[5, 6], [7,8]])

In [46]:
b

array([[5, 6],
       [7, 8]])

In [47]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [48]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])